### PR TITLE
fixed double formatting bug

### PR DESCRIPTION
**Pull request by pjohnson31**
@stiang currently if a block of text has both boldness AND italic markdown formatting, it won't be correctly stripped. This change should fix it.

### CODE REVIEW

**Comment by pjohnson31** [comment]
@stiang had any time to look at this?

**Comment by ThomasProctor** [comment]
I think this bug might be deeper than it seems, and possibly not 100% fixable. You note that `**this sentence has _double styling_**` is not stripped properly. 
Here's an example: **this sentence has _double styling_**. (Note: your test file has `**this sentence has __double styling__**`, where the double `_` and the `**` are redundant, because both produce bold.)

But some markdown editors ([dillinger](http://dillinger.io/), jupyter notebook) will produce the same result from `**this sentence has *double styling***`. unfortunately, [this might not be doable with regex](http://stackoverflow.com/a/546457/3358599).

**Comment by ThomasProctor** [comment]
Actually, I take that back; this is fixable. Since emphasis styling can only go two levels deep in markdown, all we have to do is have the `.replace(/([\*_]{1,3})(\S.*?\S)\1/g, '$2')` line repeated twice in the code. This should work for your code example, as well as with the one your code fails on that I gave.

**Comment by stiang** [comment]
Thanks! Since there are quite a few changes to the repo now (especially wrt how tests are performed), I’ve added your suggestion manually. So closing the PR, but the issue should be fixed :)

**Pull request closed without merging**
