### PR TITLE
Fix #hashtags in headers

### PR DESCRIPTION
**Pull request by fridays**
Fixes https://github.com/stiang/remove-markdown/issues/18

### CODE REVIEW

**Comment by ThomasProctor** [comment]
Thanks for noticing that! I didn't know about the common markdown spec. Might be a good idea to incorporate all the tests in that spec.

Re your fix: I think, in general, making your changes as minimal as possible is good practice. There are properties of the current version that you might miss if you re-write them from scratch. I think a minimal fix would be:
- .replace(/^\#{1,6}\s*([^#]*)\s*(\#{1,6})?/gm, '$1')
+ .replace(/^\#{1,6}\s+(.*)\s+(\#{1,6})?/gm, '$1')

By re-writing yours, you've written something that will get rid of trailing #'s even if they don't have the required leading ones.

After looking at common markdown, I actually see two other bugs in the old version:
1 It won't match anything that has a leading space
2 It won't get rid of trailing spaces after the line
This should solve those too:
/^\s{0,3}\#{1,6}\s+(.*)\s*(\#{1,6}\s*$)?/gm

I haven't actually tested this. If anyone want's to add it, you should test it first.

**Comment by ThomasProctor** [comment]
Argh. Forgot to code block things on my reply above.

**Comment by fridays** [comment]
Thanks for your response, I just pushed a fix that allows unlimited trailing hashes.

I used this tool to test the Regexp: https://regex101.com/r/BxKhFb/1

**Comment by fridays** [comment]
The suggested change was the only expression that worked for me in the end.

[CommonMark](http://commonmark.org/) was created because the [original description](http://daringfireball.net/projects/markdown/syntax) of Markdown does not specify the syntax unambiguously.

Both CommonMark and the original description seem to accept an unlimited number of trailing hashes, which doesn't need to match the number of leading hashes

**Comment by ThomasProctor** [comment]
A little problem here: @stiang has not merged any pull requests. This bug is exactly #12 

As for testing, I think that you really need to test it in the exact environment. The file includes a test file, you should add the things that break the old version to the test file, along with the output.

**Comment by fridays** [comment]
Test added. The test file expected a result where the first heading contains a trailing whitespace character, I removed that.

**Comment by stiang** [comment]
Thanks for this! Will merge this and other PRs shortly, just super busy.

**Comment by fridays** [comment]
Sounds great, thanks!

**Comment by stiang** [comment]
Sorry about the delay, I finally got around to merging this.

**Pull request merged**
